# Generated by Django 3.0.5 on 2020-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_outgoing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.CharField(max_length=60)),
                ('dests', models.CharField(max_length=60)),
            ],
        ),
    ]
