# Generated by Django 3.0.5 on 2020-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200420_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='max',
            field=models.IntegerField(),
        ),
    ]
