# Generated by Django 3.0.5 on 2020-04-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200421_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruledestination',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='api.Rule'),
        ),
    ]
