# Generated by Django 3.0.5 on 2020-04-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200421_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='PolicyRule',
        ),
        migrations.RenameModel(
            old_name='RuleDestination',
            new_name='PolicyRuleDestination',
        ),
    ]
