# Generated by Django 3.0.5 on 2020-04-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200421_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrule',
            old_name='max',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='dest',
            new_name='destination',
        ),
        migrations.AlterField(
            model_name='policyruledestination',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='api.PolicyRule'),
        ),
    ]
